---
- name: deploy capnproto services
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - "env/properties.yaml"
  roles:
    - { role: capnproto/common }
    - { role: capnproto/publisher }
    - { role: capnproto/subscriber }
  pre_tasks:
    - name: create namespace 'capnproto'
      k8s:
        name: "{{ namespace.capnproto }}"
        kind: Namespace
        state: present
        kubeconfig: "{{ minikubeconfig }}"