---
- name: deploy ingress to minikube
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - "env/properties.yaml"
    - "env/ip.yaml"
  roles:
    - { role: ingress/traefik }
    - { role: ingress/metallb }
  pre_tasks:
    - name: create k8s namespace
      shell: |
        kubectl create namespace ingress || true &&
        kubectl create namespace ingress-lb || true
