---
- name: deploy NATS JetStream
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - "env/properties.yaml"
  roles:
    - { role: messaging, tags: messaging }
  pre_tasks:
    - name: create namespace 'messaging'
      k8s:
        name: "{{ namespace.messaging }}"
        kind: Namespace
        state: present
        kubeconfig: "{{ minikubeconfig }}"