"use strict";
/* tslint:disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Person = exports.Person_Date = exports.Person_PhoneNumber = exports.Person_PhoneNumber_Type = exports._capnpFileId = void 0;
/**
 * This file has been automatically generated by the [capnpc-ts utility](https://github.com/jdiaz5513/capnp-ts).
 */
const capnp = require("capnp-ts");
const capnp_ts_1 = require("capnp-ts");
exports._capnpFileId = "fca90313fb18823f";
var Person_PhoneNumber_Type;
(function (Person_PhoneNumber_Type) {
    Person_PhoneNumber_Type[Person_PhoneNumber_Type["MOBILE"] = 0] = "MOBILE";
    Person_PhoneNumber_Type[Person_PhoneNumber_Type["HOME"] = 1] = "HOME";
    Person_PhoneNumber_Type[Person_PhoneNumber_Type["WORK"] = 2] = "WORK";
})(Person_PhoneNumber_Type = exports.Person_PhoneNumber_Type || (exports.Person_PhoneNumber_Type = {}));
class Person_PhoneNumber extends capnp_ts_1.Struct {
    getNumber() { return capnp_ts_1.Struct.getText(0, this); }
    setNumber(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getType() { return capnp_ts_1.Struct.getUint16(0, this); }
    setType(value) { capnp_ts_1.Struct.setUint16(0, value, this); }
    toString() { return "Person_PhoneNumber_" + super.toString(); }
}
exports.Person_PhoneNumber = Person_PhoneNumber;
Person_PhoneNumber.Type = Person_PhoneNumber_Type;
Person_PhoneNumber._capnp = { displayName: "PhoneNumber", id: "9bf13aefaab5136d", size: new capnp_ts_1.ObjectSize(8, 1) };
class Person_Date extends capnp_ts_1.Struct {
    getYear() { return capnp_ts_1.Struct.getInt16(0, this); }
    setYear(value) { capnp_ts_1.Struct.setInt16(0, value, this); }
    getMonth() { return capnp_ts_1.Struct.getUint8(2, this); }
    setMonth(value) { capnp_ts_1.Struct.setUint8(2, value, this); }
    getDay() { return capnp_ts_1.Struct.getUint8(3, this); }
    setDay(value) { capnp_ts_1.Struct.setUint8(3, value, this); }
    toString() { return "Person_Date_" + super.toString(); }
}
exports.Person_Date = Person_Date;
Person_Date._capnp = { displayName: "Date", id: "a5e6c26cee9f9762", size: new capnp_ts_1.ObjectSize(8, 0) };
class Person extends capnp_ts_1.Struct {
    getName() { return capnp_ts_1.Struct.getText(0, this); }
    setName(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getEmail() { return capnp_ts_1.Struct.getText(1, this); }
    setEmail(value) { capnp_ts_1.Struct.setText(1, value, this); }
    adoptPhones(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownPhones() { return capnp_ts_1.Struct.disown(this.getPhones()); }
    getPhones() { return capnp_ts_1.Struct.getList(2, Person._Phones, this); }
    hasPhones() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initPhones(length) { return capnp_ts_1.Struct.initList(2, Person._Phones, length, this); }
    setPhones(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    adoptBirthdate(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(3, this)); }
    disownBirthdate() { return capnp_ts_1.Struct.disown(this.getBirthdate()); }
    getBirthdate() { return capnp_ts_1.Struct.getStruct(3, Person_Date, this); }
    hasBirthdate() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(3, this)); }
    initBirthdate() { return capnp_ts_1.Struct.initStructAt(3, Person_Date, this); }
    setBirthdate(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(3, this)); }
    toString() { return "Person_" + super.toString(); }
}
exports.Person = Person;
Person.PhoneNumber = Person_PhoneNumber;
Person.Date = Person_Date;
Person._capnp = { displayName: "Person", id: "c80dfc20bc049168", size: new capnp_ts_1.ObjectSize(0, 4) };
Person._Phones = capnp.CompositeList(Person_PhoneNumber);
