---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard-http
  namespace: ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web

spec:
  entryPoints:
    - traefik
  routes:
    - match: Host(`ingress.minikube`) && PathPrefix(`/dashboard`)
      kind: Rule
      services:
        - name: traefik
          port: 9000
    - match: Host(`ingress.minikube`) && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: traefik
          port: 9000