---
- name: add hostnames to /etc/hosts
  vars:
    comment: '# added by ansible'
  lineinfile:
    dest: /etc/hosts
    regexp: "ingress.minikube"
    line: "{{ minikube_ip }} ingress.minikube {{ comment }}"
    state: present
    backup: no
