---
- name: configure and start minikube
  shell: |
    minikube start --cpus={{ num_cpu }} --disk-size={{ size_disk }} --memory={{ memory }} --kubernetes-version={{ k8s_version }} --extra-config=apiserver.service-node-port-range=80-30000

- name: get minikube ip
  shell: |
    minikube ip
  register: minikube_ip

- name: save minikube ip
  template:
    src: ip.yaml.j2
    dest: "{{ playbook_dir }}/env/ip.yaml"
