/**
 * This file has been automatically generated by the [capnpc-ts utility](https://github.com/jdiaz5513/capnp-ts).
 */
import * as capnp from "capnp-ts";
import { Struct as __S } from 'capnp-ts';
export declare const _capnpFileId = "b517f58004a64978";
export declare enum Person_PhoneNumber_Type {
    MOBILE = 0,
    HOME = 1,
    WORK = 2
}
export declare class Person_PhoneNumber extends __S {
    static readonly Type: typeof Person_PhoneNumber_Type;
    static readonly _capnp: {
        displayName: string;
        id: string;
        size: capnp.ObjectSize;
    };
    getNumber(): string;
    setNumber(value: string): void;
    getType(): Person_PhoneNumber_Type;
    setType(value: Person_PhoneNumber_Type): void;
    toString(): string;
}
export declare class Person_Date extends __S {
    static readonly _capnp: {
        displayName: string;
        id: string;
        size: capnp.ObjectSize;
    };
    getYear(): number;
    setYear(value: number): void;
    getMonth(): number;
    setMonth(value: number): void;
    getDay(): number;
    setDay(value: number): void;
    toString(): string;
}
export declare class Person extends __S {
    static readonly PhoneNumber: typeof Person_PhoneNumber;
    static readonly Date: typeof Person_Date;
    static readonly _capnp: {
        displayName: string;
        id: string;
        size: capnp.ObjectSize;
    };
    static _Phones: capnp.ListCtor<Person_PhoneNumber>;
    getName(): string;
    setName(value: string): void;
    getEmail(): string;
    setEmail(value: string): void;
    adoptPhones(value: capnp.Orphan<capnp.List<Person_PhoneNumber>>): void;
    disownPhones(): capnp.Orphan<capnp.List<Person_PhoneNumber>>;
    getPhones(): capnp.List<Person_PhoneNumber>;
    hasPhones(): boolean;
    initPhones(length: number): capnp.List<Person_PhoneNumber>;
    setPhones(value: capnp.List<Person_PhoneNumber>): void;
    adoptBirthdate(value: capnp.Orphan<Person_Date>): void;
    disownBirthdate(): capnp.Orphan<Person_Date>;
    getBirthdate(): Person_Date;
    hasBirthdate(): boolean;
    initBirthdate(): Person_Date;
    setBirthdate(value: Person_Date): void;
    toString(): string;
}
