---
- name: deploy message-publisher
  k8s:
    kubeconfig: "{{ minikubeconfig}}"
    state: present
    resource_definition: "{{ lookup('template', 'deployments.yaml.j2') | from_yaml }}"

- name: deploy message-publisher-service
  k8s:
    kubeconfig: "{{ minikubeconfig}}"
    state: present
    resource_definition: "{{ lookup('template', 'services.yaml.j2') | from_yaml }}"

- name: deploy message-publisher-ingress
  k8s:
    kubeconfig: "{{ minikubeconfig}}"
    state: present
    resource_definition: "{{ lookup('template', 'ingress-routes.yaml.j2') | from_yaml }}"